### ISSUE TITLE
cacheManager 테스트 관련 버그

### ISSUE THREAD

**Issue by ydh6226** [clone-market/market-backend#19]
# 버그
테스트를 한번에 여러개 돌릴경우 cacheManger 관련하여 아래와 같은 내용의 예외가 발생합니다.
```
nested exception is net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM
```

# 원인
하나의 테스트클래스 마다 cacheManger를 생성하는데 
두번째 테스트 부터 이전 테스트에서 생성한 cacheManger때문에 
같은 이름을 가진 cacheManger가 생성이 될 수 없고 따라서 예외가 발생합니다.

# 해결
cacheManger를 싱글톤으로 설정하여 문제를 해결할 수 있습니다.

**Comment by gunkim** [comment]
음... 사실 저도 전체 테스트를 진행해보다가 이런 오류가 발생했었는데 무심코 넘겼던거 같은데 이슈 남겨주셨네요.
말씀하신대로 이 부분은 싱글톤 패턴을 적용하면 될 것 같습니다!

**Comment by ydh6226** [comment]
넵 수정해서 PR하겠습니다.
