### ISSUE TITLE
커스텀 레포지토리 적용하기

### ISSUE THREAD

**Issue by gunkim** [clone-market/market-backend#7]
Querydsl 레포지토리와 Jpa 레포지토리를 공동으로 사용할 수 있도록 커스텀 레포지토리 적용이 필요합니다.

**Comment by gunkim** [comment]
음... 만들다 보니 쓸데없이 생성되는 파일이 많아져서 복잡해지는 경향이 있는 것 같습니다. 
필요 시에 생성해서 사용하는 것이 좋을 것 같네요.

**Comment by ydh6226** [comment]
넵 jpa로만 해결가능한 리포지토리도 있으니까 필요할때 추가하면 될것같아요
